Repository Manthan933/Manthan, pull requests merged in 2021-05, with the labels that each got.

#192 Updated footer in all pages
  client/package-lock.json
  client/src/components/auth/Login.js
  client/src/components/auth/Register.js
  client/src/components/classroom/Classroom.js
  client/src/components/dashboard/Dashboard.js
  client/src/components/layout/Landing.js
  client/src/components/layout/landing.module.css
Labels: Level2, gssoc21

#196 login icon added
  client/src/components/layout/Navbar.js
Labels: Level0, gssoc21

#186 Subject Code Added
  client/src/components/classroom/Classroom.js
Labels: Level0, gssoc21

#211 make homepage responsive
  client/src/components/layout/landing.module.css
Labels: Level1, gssoc21

#208 Remember me feature added
  client/src/actions/auth.js
  client/src/components/auth/Login.js
  routes/api/auth.js
Labels: Level1, gssoc21

#218 removing the extra footer
  client/src/App.js
Labels: gssoc21

#219 opacity to background image
  client/src/App.js
Labels: Level0, gssoc21

#221 Update Readme.md
  README.md
Labels: Level0, gssoc21

#224 Improvement in the Home Page and Change in Font in theme settings
  client/package-lock.json
  client/src/components/dashboard/Dashboard.js
  client/src/components/layout/landing.module.css
  client/src/components/themes/Theme.js
  package-lock.json
Labels: Level1, gssoc21
