Repository Manthan933/Manthan, pull requests merged in 2021-03, with the labels that each got.

#89 Added start script
  server/package.json
Labels: Level0, gssoc21

#102 Updated ClassCard.js
  client/src/components/ClassCard/ClassCard.js
Labels: Level1, gssoc21

#107 class link
  README.md
  client/public/index.html
  client/src/actions/actions.js
  client/src/components/Froms/handleFormError.js
  client/src/views/App.js
  client/src/views/classroom/Classroom.js
  client/src/views/joinClassWithLink/JoinClass.js
  client/src/views/main/Main.js
  server/models/classrooms.model.js
Labels: Level2, gssoc21

#105 perf(code generation): used randomatic to geneate a more random and r…
  client/package-lock.json
  package-lock.json
  package.json
  server/controllers/classrooms.js
Labels: Level2, gssoc21

#114 added docker support to readme file
  README.md
Labels: Level0, gssoc21

#117 Update README.md
  README.md
Labels: Level0, gssoc21

#115 Updated Navbar.js
  client/src/components/Navbar/Navbar.js
Labels: Level0, gssoc21

#132 added a homepage
  client/public/index.html
  client/src/assets/images/book-pen.png
  client/src/views/App.js
  client/src/views/home/Home.js
  client/src/views/home/home.module.css
Labels: Level2, gssoc21

#118 search box added
  client/src/actions/actions.js
  client/src/views/App.js
  client/src/views/main/Main.js
Labels: Level2, gssoc21
